import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import GameList from './components/GameList'
import CategoryList from './components/CategoryList'
import { useState } from 'react'
import { SWRConfig } from 'swr'
import getCategories from './api/categories'
import getGamesByCategory from './api/games'

export async function getStaticProps() {
  const categories = await getCategories()
  return {
    props: {
      fallback: {
        'categories': categories
      }
    }
  }
}

export default function Home({ fallback }) {
  const [games, setGames] = useState([])
  const [category, setCategory] = useState("")
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to board game search!
        </h1>
        <SWRConfig value={{ fallback }}>
          <CategoryList categoryList={ fallback.categories } setCategory={setCategory} />
        </SWRConfig>
        <GameList category={category}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
