import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'

const fetcher = (url) => fetch('https://api.boardgameatlas.com/api/search?order_by=rank&ascending=false&client_id=JLBr5npPhV').then((res) => res.json())

// function Profile() {
//   const { data, error } = useSWR('/api/user', fetcher)

//   if (error) return <div>failed to load</div>
//   if (!data) return <div>loading...</div>
//   return <div>hello {data.name}!</div>
// }

export default function Home() {
  const { data, error } = useSWR('/api/user', fetcher)
  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  // var gameNameList = data.games.map(e => e.name)
  console.log(data.games[2])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to board game search!
        </h1>

        <div className={styles.list}>
        {data.games.map(function(game, id){
          return (
            <div key={id}>
              <h3 id="name">{game.name}</h3>
              {/* <p>{game.description_preview}</p> */}
              <Image id="cover" alt="game cover" width="200" height="200"src={game.image_url}></Image>
              <p id="rating">Rating: {game.average_user_rating.toFixed(2)}</p>
              <p id="learning-complexity">Learning complexity: {game.average_learning_complexity.toFixed(2)}</p>
            </div>
          )
        })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
