name: "Deploy to Preview"
on:
  pull_request:
    branches:
      - dev

jobs:
  vercel: 
    runs-on: ubuntu-latest
    name: "Deploy PR Preview"
    outputs:
      url: ${{ steps.pr-preview.outputs.url }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: "Deploy to Preview"
        id: pr-preview
        run: |
          npx vercel --token ${VERCEL_TOKEN}  > deployment-url.txt
          echo "::set-output name=url::$(cat deployment-url.txt)"

        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

  comment:
    name: "Comment Preview URL"
    runs-on: ubuntu-latest
    needs: vercel
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview deployment URL: ${{ needs.vercel.outputs.url }}`
            })

  test:
    runs-on: ubuntu-latest
    name: Run E2E tests
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Execute robot tests
      uses: joonvena/robotframework-docker-action@v1.0
      needs: vercel
      env:
        HOME_PAGE:  ${{ needs.vercel.outputs.url }}
        BROWSER:    firefox
        TEST_DIR:   robot/e2e
        REPORT_DIR: robot/e2e/reports
      with:
        robot_tests_dir:   ${{ env.TEST_DIR }}
        robot_reports_dir: ${{ env.REPORT_DIR }}
        robot_options:     "--variable BROWSER:${{ env.BROWSER }} --variable HOME_PAGE:${{ env.HOME_PAGE }}"

    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: robot/e2e/reports